name: Build 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    

    - name: Build & Push Docker
      run: |
        docker login ${{ secrets.REGISTRY }}
        docker build -t cls.im/utility/qbittorrent:latest .
        docker push cls.im/utility/qbittorrent:latest
