name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
        
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u wzhone --password-stdin registry.hub.docker.com
        docker build -t qbittorrent:latest .
        docker tag qbittorrent:latest wzhone/qbittorrent:latest
        docker push wzhone/qbittorrent:latest
        
